# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  shared-network:
    driver: bridge

services:

  # This starts a local PostgreSQL DB.
  db:
    container_name: sales_db
    networks:
      - shared-network
    image: postgres:11.1-alpine
    ports:
      - 5432:5432

  # This is the core CRUD based service.
  sales-api:
    container_name: sales-api
    networks:
      - shared-network
    image: sales-api-amd64:1.0
    ports:
      - 3000:3000 # CRUD API
      - 4000:4000 # DEBUG API
    environment:
      - SALES_DB_HOST=db
      - SALES_DB_DISABLE_TLS=1 # This is only disabled for our development enviroment.
      # - GODEBUG=gctrace=1
    depends_on:
      - db
